### ISSUE TITLE
YAML preview pane indents lists but most people seem not to.

### ISSUE THREAD

**Issue by chuckha** [heptio/vscode-jsonnet#51]
If this is actually a style preference you can feel free to close.

In most YAML I read I see lists that look like this:

```yaml
listname:
- item1
- item2
- item3
```

But the preview pane generates:
```yaml
listname:
  - item1
  - item2
  - item3
```

Which causes unnecessary indentation and for exceptionally deep items this does add up (for instance:

```yaml
apiVersion: v1
items:
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
    spec:
      rules:
        - host: something.example.com
          http:
            paths:
              - backend:
                  serviceName: something
```
has an extra  3 layers of indentation (because it's nested  in 3 layers of lists)
